
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Fallback placeholder so `prisma generate` (postinstall/CI/Vercel install)
    // never crashes when DATABASE_URL is absent. Generate doesn't connect to
    // the DB; any command that does (migrate deploy, the app) still needs the
    // real variable set.
    url:
      process.env.DATABASE_URL ??
      "postgresql://localhost:5432/placeholder?schema=public",
  },
});
